name: Build builder
description: Builds the Docker builder image using BuildKit and GitHub Actions cache

inputs:
  name:
    description: Name of the builder image
    required: true
  context:
    description: Path to the build context
    required: false
    default: "."
  file:
    description: Path to Dockerfile with the builder stage
    required: true
  target:
    description: Name of the target to build
    required: false
    default: builder

runs:
  using: composite
  steps:
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-${{ inputs.name }}-cache
        key: ${{ runner.os }}-buildx-${{ inputs.name }}-${{ github.sha }}
        restore-keys: |
            ${{ runner.os }}-buildx-${{ inputs.name }}-
    - name: Build builder
      uses: docker/build-push-action@v3
      with:
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        target: ${{ inputs.target }}
        tags: ${{ inputs.name }}
        load: true
        cache-from: type=local,src=/tmp/.buildx-${{ inputs.name }}-cache
        cache-to: type=local,dest=/tmp/.buildx-${{ inputs.name }}-cache-new,mode=max
    - name: Use new cache
      shell: bash
      run: |
          rm -rf /tmp/.buildx-${{ inputs.name }}-cache
          mv /tmp/.buildx-${{ inputs.name }}-cache-new /tmp/.buildx-${{ inputs.name }}-cache