name: Build builder
description: Builds the Docker builder image using BuildKit and GitHub Actions cache

inputs:
  name:
    description: Name of the builder image
    required: true
  context:
    description: Path to the build context
    required: false
    default: "."
  file:
    description: Path to Dockerfile with the builder stage
    required: true
  target:
    description: Name of the target to build
    required: false
    default: builder
  cache_key:
    description: Key of the GitHub Actions cache
    required: false
    default: ${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}

runs:
  using: composite
  steps:
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/buildx-cache/${{ inputs.cache_key }}
        key: ${{ inputs.cache_key }}-${{ github.sha }}
        restore-keys: |
            ${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-
            ${{ runner.os }}-${{ github.job }}-
    - name: Build builder
      uses: docker/build-push-action@v3
      with:
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        target: ${{ inputs.target }}
        tags: ${{ inputs.name }}
        load: true
        cache-from: type=local,src=/tmp/buildx-cache/${{ inputs.cache_key }}
        cache-to: type=local,dest=/tmp/buildx-cache/${{ inputs.cache_key }}-new,mode=max
    - name: Use new cache
      shell: bash
      run: |
          rm -rf /tmp/buildx-cache/${{ inputs.cache_key }}
          mv /tmp/buildx-cache/${{ inputs.cache_key }}-new /tmp/buildx-cache/${{ inputs.cache_key }}