version: '3'

output: prefixed

vars:
  PROJECT_ROOT:
    sh: pwd

includes:
  interface_service:
    dir: ./interface_service
    taskfile: ./interface_service
  learning_service:
    dir: ./learning_service
    taskfile: ./learning_service
  dev: ./dev
  dist: ./dist

tasks:
  prepare:
    - task: interface_service:prepare
    - task: learning_service:prepare
  build_docker:
    - task: interface_service:build_docker
    - task: learning_service:build_docker
  clean:pycache: find . -type d -name "__pycache__" -exec rm -rf {} +
  clean:
    - task: interface_service:clean
    - task: learning_service:clean
    - task: clean:pycache
