services:
  minio-init:
    image: busybox:1.35
    entrypoint: >
      sh -c "
        mkdir -p /minio-data/stackoverflow-tagger
      "
    volumes:
      - "minio-data:/minio-data"
  minio:
    image: minio/minio:RELEASE.2022-05-08T23-50-31Z
    ports:
      - "9000:9000"
      - "9001:9001"
    command:
      - "server"
      - "/data"
      - "--console-address"
      - ":9001"
    volumes:
      - "minio-data:/data"
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "remla2022"
    depends_on:
      minio-init:
        condition: service_completed_successfully
  pubsub:
    image: google/cloud-sdk:385.0.0-emulators
    ports:
      - "8085:8085"
    entrypoint: "gcloud beta emulators pubsub start"
    command:
      - "--data-dir=/data"
    volumes:
      - "pubsub-data:/data"

volumes:
  minio-data: {}
  pubsub-data: {}
