name: Build and push Docker image
description: Builds and pushes docker images for the given details

inputs:
  context:
    description: Docker context for the build-push action
    required: true
  file:
    description: Path to the dockerfile
    required: true
  image:
    description: The name of the image
    required: true
  push:
    description: Whether to push the image to the registry
    required: true
  cache_key:
    description: Key of the GitHub Actions cache
    required: false
    default: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ github.ref_name }}

runs:
  using: composite
  steps:
    - name: Gather metadata
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.image }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.0.') }}
          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
          latest
    - name: Prepare Docker layer cache
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ inputs.cache_key }}-${{ github.sha }}
        restore-keys: |
          ${{ inputs.cache_key }}
          ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: ${{ inputs.push }}
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    - name: Move cache
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      # https://github.com/moby/buildkit/issues/2887
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache