name: Build and push Docker image
description: Builds and pushes docker images for the given details

inputs:
  context:
    description: Docker context for the build-push action
    required: true
  file:
    description: Path to the dockerfile
    required: true
  image:
    description: The name of the image
    required: true
  push:
    description: Whether to push the image to the registry
    required: true

runs:
  using: composite
  steps:
    - name: Gather metadata
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.image }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.0.') }}
          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
          latest
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: ${{ inputs.push }}  
        tags: ${{ steps.metadata.outputs.tags }}  
        labels: ${{ steps.metadata.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        