apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stackoverflow-tagger.interfaceService.configMap" . }}
  labels:
    {{- include "stackoverflow-tagger.labels" . | nindent 4 }}
data:
  REMLA_MODEL_LOCAL_PATH: "/app/output/model.joblib"
  {{- include "stackoverflow-tagger.config.objectStorage" . | nindent 2 }}
  {{- include "stackoverflow-tagger.config.pubsub" . | nindent 2 }}