apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackoverflow-tagger.interfaceService.configMap" . }}
  labels:
    {{- include "stackoverflow-tagger.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "stackoverflow-tagger.config.objectStorage.credentials" . | nindent 2 }}
