apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stackoverflow-tagger.learningService.configMap" . }}
  labels:
    {{- include "stackoverflow-tagger.labels" . | nindent 4 }}
data:
  REMLA_DATA_DIR: "/app/data"
  REMLA_DATASET_FOR_TRAINING_DIR: "/app/training"
  REMLA_OUTPUT_DIR: "/app/output"
  REMLA_MODEL_LOCAL_PATH: "/app/output/model.joblib"
  {{- include "stackoverflow-tagger.config.objectStorage" . | nindent 2 }}
  {{- include "stackoverflow-tagger.config.pubsub" . | nindent 2 }}