apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stackoverflow-tagger.learningService.configMap" . }}
  labels:
    {{- include "stackoverflow-tagger.labels" . | nindent 4 }}
data:
  REMLA_DATA_DIR: "/app/data"
  REMLA_DATASET_FOR_TRAINING_DIR: "/app/training"
  REMLA_OUTPUT_DIR: "/app/output"
  REMLA_MODEL_LOCAL_PATH: "/app/output/model.joblib"
  REMLA_CLASSIFIER_OBJECT_KEY: "classifier.joblib"
  REMLA_CLASSIFIER_LOCAL_PATH: "/app/output/classifier.joblib"
  REMLA_PREPROCESSOR_DATA_PATH: "/app/output/preprocessor_data.joblib"
  REMLA_PREPROCESSOR_DATA_OBJECT_KEY: "preprocessor_data.joblib"
  REMLA_PREPROCESSOR_LABELS_PATH: "/app/output/preprocessor_labels.joblib"
  REMLA_PREPROCESSOR_LABELS_OBJECT_KEY: "preprocessor_labels.joblib"
  REMLA_PUBSUB_DATA_TEMP_FILE: "/app/data/incoming.tsv"
  {{- include "stackoverflow-tagger.config.objectStorage" . | nindent 2 }}
  {{- include "stackoverflow-tagger.config.pubsub" . | nindent 2 }}