{{- if .Values.learningService.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stackoverflow-tagger.learningService.serviceAccountName" . }}
  labels:
    {{- include "stackoverflow-tagger.labels" . | nindent 4 }}
  {{- with .Values.learningService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
