ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ${STATIC_IP_NAME}
    networking.gke.io/managed-certificates: ${INGRESS_MANAGED_CERTIFICATE_NAME}
  hosts:
    - ${HOSTNAME}

learningService:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9010"
    prometheus.io/path: "/"

interfaceService:
  replicaCount: ${INTERFACE_SERVICE_REPLICA_COUNT}
  service:
    # Required for GKE Ingress
    type: NodePort
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
    prometheus.io/path: "/"

frontend:
  replicaCount: ${FRONTEND_REPLICA_COUNT}
  service:
    # Required for GKE Ingress
    type: NodePort

gcloud:
  podMonitoring:
    enabled: true