version: '3'

vars:
  LEARNING_SERVICE_BUILDER_IMAGE: remla-stackoverflow-tagger/learning-service-builder
  LEARNING_SERVICE_IMAGE: remla-stackoverflow-tagger/learning-service
  PATH: learning_service
  VENV: learning_venv

tasks:
  create_venv:
    preconditions:
      - sh: 'python -c "import sys; assert sys.version_info.major == 3 and 6 <= sys.version_info.minor <= 9"'
        msg: 'Requires Python version >=3.6 and <=3.9'
    status: ["test -d {{.VENV}}"]
    cmds: ["python -m venv {{.VENV}}"]
  prepare:
    deps: [create_venv]
    cmds:
      - "{{.VENV}}/bin/pip install --upgrade pip wheel"
      - "{{.VENV}}/bin/pip install -r requirements.txt"
  clean: "rm -rf {{.VENV}}"
  lint: "pylint --rcfile=.pylintrc src/"
  test: "pytest -n auto"
  mllint: "mllint --output report.md"
  build_builder:
    cmds: [ "docker build --target builder -t {{.LEARNING_SERVICE_BUILDER_IMAGE}} ." ]
  build_docker:
    cmds: [ "docker build --target final -t {{.LEARNING_SERVICE_IMAGE}} ." ]
  docker_run:
    deps: [ build_builder ]
    interactive: true
    vars:
      UID:
        sh: id -u
      GID:
        sh: id -g
    cmds:
      - >
        docker run -it --rm
        --network host
        --user {{.UID}}:{{.GID}}
        --workdir /project
        --volume {{.PROJECT_ROOT}}/learning_service:/project
        {{.LEARNING_SERVICE_BUILDER_IMAGE}}
        {{.CLI_ARGS}}