# All other envrionments inherit from default
default:
  name: default
  host: server.com from YAML
  port: 5000
  username: admin
development:
  name: dev
  custom: 'this is custom from [development]'
  host: dev_server.com from yaml
  works: yaml_example in dev env
production:
  name: prod
  custom: 'this is custom from [production]'
  host: prod_server.com from yaml
  works: yaml_example in prod env