version: '3'

vars:
  HELM_BUILDER_IMAGE: remla-stackoverflow-tagger/helm-builder
  # Overridden by GitHub Actions
  VERSION: '{{ .VERSION | default "1.0.0-DEV" }}'
  HELM_PACKAGE_DIR: helm/charts

tasks:
  lint: "helm lint helm/stackoverflow-tagger"
  package: "helm package helm/stackoverflow-tagger --version 0.0.1 --app-version {{.VERSION}} -d {{.HELM_PACKAGE_DIR}}"
  build_builder: "docker build --target builder -t {{.HELM_BUILDER_IMAGE}} -f helm/Dockerfile ."
  docker_run:
    deps: [ build_builder ]
    interactive: true
    vars:
      UID:
        sh: id -u
      GID:
        sh: id -g
    cmds:
      - >
        docker run -it --rm
        --network host
        --user {{.UID}}:{{.GID}}
        --workdir /project
        --volume {{.PROJECT_ROOT}}:/project
        {{.HELM_BUILDER_IMAGE}}
        {{.CLI_ARGS}}
  clean:
    - rm -rf {{.HELM_PACKAGE_DIR}}