version: '3'

vars:
  INTERFACE_SERVICE_BUILDER_IMAGE: remla-stackoverflow-tagger/interface-service-builder
  INTERFACE_SERVICE_IMAGE: remla-stackoverflow-tagger/interface-service
  PYTHON_BIN: python
  ENV: interface_venv

tasks:
  create_venv:
    status:
      - "test -f ${{.ENV}}/bin/activate"
    cmds:
      - "{{.PYTHON_BIN}} -m venv {{.ENV}}"
      - "{{.ENV}}/bin/python3 -m pip install -U pip setuptools wheel"
  prepare:
    sources:
      - "{{.ENV}}/bin/activate"
    deps:
      - task: create_venv
        vars:
          ENV: "{{.ENV}}"
    cmds:
      - "{{.ENV}}/bin/pip install -r requirements.txt"
  clean:
    - rm -rf interface_venv
  build_builder:
    cmds: ["docker build --target builder -t {{.INTERFACE_SERVICE_BUILDER_IMAGE}} ."]
  build_docker:
    cmds: ["docker build -t {{.INTERFACE_SERVICE_IMAGE}} ."]
  docker_run:
    deps: [build_builder]
    interactive: true
    vars:
      UID:
        sh: id -u
      GID:
        sh: id -g
    cmds:
      - >
        docker run -it --rm
        --network host
        --user {{.UID}}:{{.GID}}
        --workdir /project
        --volume {{.PROJECT_ROOT}}/interface_service:/project
        {{.INTERFACE_SERVICE_BUILDER_IMAGE}}
        {{.CLI_ARGS}}
  lint:
    - "{{.ENV}}/bin/pylint --rcfile=.pylintrc src/"
  test:
    - "{{.ENV}}/bin/pytest"
