name: Deploy

on:
  workflow_call:
    inputs:
      chart_version:
        description: 'Release tag to deploy'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to deploy'
        type: string
        required: true
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true

jobs:
  deploy_test:
    name: 'Deploy test'
    # inputs.environment equal to 0 means that the workflow was executed with workflow_call
    if: inputs.environment == 0 || inputs.environment == 'test'
    environment: test
    concurrency: deploy-test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - id: version
        name: Determine version from tag
        uses: ./.github/actions/read_tag
        with:
          tag: ${{ inputs.tag }}
      - name: Deploy Terraform
        uses: ./.github/actions/deploy
        with:
          project_id: remla2022-test
          tfvars_file: test.tfvars
          terraform_sa_key_base64: ${{ secrets.TERRAFORM_SA_KEY_BASE64 }}
          chart_version: ${{ steps.version.outputs.version }}
  deploy_production:
    name: 'Deploy production'
    # inputs.environment equal to 0 means that the workflow was executed with workflow_call
    if: inputs.environment == 0 || inputs.environment == 'production'
    environment: production
    concurrency: deploy-production
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - id: version
        name: Determine version from tag
        uses: ./.github/actions/read_tag
        with:
          tag: ${{ inputs.tag }}
      - name: Deploy Terraform
        uses: ./.github/actions/deploy
        with:
          project_id: remla2022-prod
          tfvars_file: production.tfvars
          terraform_sa_key_base64: ${{ secrets.TERRAFORM_SA_KEY_BASE64 }}
          chart_version: ${{ steps.version.outputs.version }}
