name: Build

on:
  push
    # tags: ["v[0-9]+.[0-9]+.[0-9]+"]

env:
  IMG: ${{ github.repository }}
  REGISTRY: ghcr.io

# Learning service
jobs:
  learning-service:
    # Only run on master
    # if: github.event.base_ref=='refs/heads/master'
    name: Build and push learning service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to image registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: ./.github/actions/build_and_push
        with:
          context: ./src
          file: ./src/Dockerfile
          img: ${{ env.REGISTRY }}/${{ env.IMG }}/learning_service

# Other service
  interface-service:
    name: Build and push the interface service
    # Only run on master
    # if: github.event.base_ref=='refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to image registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: ./.github/actions/build_and_push
        with:
          context: ./interface_service
          file: ./interface_service/Dockerfile
          img: ${{ env.REGISTRY }}/${{ env.IMG }}/interface_service