name: Build

on:
  pull_request:
    branches: [ master ]
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

env:
  IMG: ${{ github.repository }}
  REGISTRY: ghcr.io


jobs:

  # Learning service
  learning-service:
    name: Build and push learning service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to image registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: ./.github/actions/build_and_push
        with:
          context: ./learning_service
          file: ./learning_service/Dockerfile
          img: ${{ env.REGISTRY }}/${{ env.IMG }}/learning_service

  # Interface service
  interface-service:
    name: Build and push the interface service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to image registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: ./.github/actions/build_and_push
        with:
          context: ./interface_service
          file: ./interface_service/Dockerfile
          img: ${{ env.REGISTRY }}/${{ env.IMG }}/interface_service