name: Verify Terraform

on:
  push:
    tags-ignore: [ 'v*.*.*' ]
    branches-ignore: [ 'gh-pages' ]
    paths:
      - terraform/**
  pull_request:
    paths:
      - terraform/**

env:
  TERRAFORM_BUILDER_NAME: terraform-builder:latest

jobs:
  verify-formatting:
    name: Verify formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Prepare builder
        uses: ./.github/actions/builder
        with:
          file: terraform/Dockerfile
          context: terraform
          name: ${{ env.TERRAFORM_BUILDER_NAME }}
      - name: Verify Terraform files formatting
        uses: ./.github/actions/builder_run
        with:
          image: ${{ env.TERRAFORM_BUILDER_NAME }}
          command: task terraform:fmt -- --check
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Prepare builder
        uses: ./.github/actions/builder
        with:
          file: terraform/Dockerfile
          context: terraform
          name: ${{ env.TERRAFORM_BUILDER_NAME }}
      - name: Initialize Terraform
        uses: ./.github/actions/builder_run
        with:
          image: ${{ env.TERRAFORM_BUILDER_NAME }}
          command: task terraform:run -- init --backend=false
      - name: Validate Terraform files
        uses: ./.github/actions/builder_run
        with:
          image: ${{ env.TERRAFORM_BUILDER_NAME }}
          command: task terraform:validate