name: Verify

on:
  push:
    tags-ignore: [ 'v*.*.*' ]
    branches-ignore: [ 'gh-pages' ]

env:
  INTERFACE_SERVICE_BUILDER_NAME: interface-service-builder:latest
  LEARNING_SERVICE_BUILDER_NAME: learning-service-builder:latest
  FRONTEND_BUILDER_NAME: frontend-builder:latest
  HELM_BUILDER_NAME: helm-builder:latest

jobs:
  lint-interface-service:
    name: Lint interface service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Prepare builder
        uses: ./.github/actions/builder
        with:
          file: interface_service/Dockerfile
          context: interface_service
          name: ${{ env.INTERFACE_SERVICE_BUILDER_NAME }}
      - name: Lint interface service
        uses: ./.github/actions/builder_run
        with:
          image: ${{ env.INTERFACE_SERVICE_BUILDER_NAME }}
          command: task interface_service:lint
  lint-learning-service:
    name: Lint learning service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Prepare builder
        uses: ./.github/actions/builder
        with:
          file: learning_service/Dockerfile
          context: learning_service
          name: ${{ env.LEARNING_SERVICE_BUILDER_NAME }}
      - name: Lint learning service
        uses: ./.github/actions/builder_run
        with:
          image: ${{ env.LEARNING_SERVICE_BUILDER_NAME }}
          command: task learning_service:lint
  lint-frontend:
    name: Lint frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Prepare builder
        uses: ./.github/actions/builder
        with:
          file: frontend/Dockerfile
          context: frontend
          name: ${{ env.FRONTEND_BUILDER_NAME }}
      - name: Lint Helm Chart
        uses: ./.github/actions/builder_run
        with:
          image: ${{ env.FRONTEND_BUILDER_NAME }}
          command: task frontend:lint
  lint-helm:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Prepare builder
        uses: ./.github/actions/builder
        with:
          file: helm/Dockerfile
          name: ${{ env.HELM_BUILDER_NAME }}
      - name: Lint learning service
        uses: ./.github/actions/builder_run
        with:
          image: ${{ env.HELM_BUILDER_NAME }}
          command: task helm:lint
