name: Verify

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Prepare builder
        uses: ./.github/actions/builder
      - name: Lint interface service
        uses: ./.github/actions/builder_run
        with:
          command: task interface_service:lint
      - name: Lint learning service
        uses: ./.github/actions/builder_run
        with:
          command: task learning_service:lint
